tarot_card_mapping = {
    # Major Arcana Cards
    "The Fool": "New beginnings, spontaneity, free spirit, potential.",
    "The Magician": "Manifestation, resourcefulness, power, inspired action.",
    "The High Priestess": "Intuition, subconscious, mystery, divine femininity.",
    "The Empress": "Abundance, creativity, nurture, fertility.",
    "The Emperor": "Authority, structure, stability, father figure.",
    "The Hierophant": "Tradition, spirituality, guidance, education.",
    "The Lovers": "Love, harmony, partnerships, alignment of values.",
    "The Chariot": "Control, willpower, determination, success.",
    "Strength": "Courage, confidence, compassion, inner strength.",
    "The Hermit": "Introspection, solitude, inner guidance, reflection.",
    "Wheel of Fortune": "Luck, karma, cycles of life, turning points.",
    "Justice": "Fairness, truth, law, accountability.",
    "The Hanged Man": "Pause, surrender, letting go, new perspective.",
    "Death": "Transformation, endings, new beginnings, transition.",
    "Temperance": "Balance, moderation, patience, harmony.",
    "The Devil": "Addiction, materialism, entrapment, shadow self.",
    "The Tower": "Sudden change, upheaval, chaos, revelation.",
    "The Star": "Hope, inspiration, renewal, spirituality.",
    "The Moon": "Illusion, fear, intuition, subconscious.",
    "The Sun": "Positivity, success, joy, vitality.",
    "Judgement": "Reflection, reckoning, awakening, inner calling.",
    "The World": "Completion, accomplishment, travel, integration.",
    
    # Wands Suit
    "Ace of Wands": "Inspiration, new opportunities, creativity, potential.",
    "Two of Wands": "Planning, progress, decisions, discovery.",
    "Three of Wands": "Expansion, foresight, leadership, exploration.",
    "Four of Wands": "Celebration, harmony, homecoming, community.",
    "Five of Wands": "Conflict, competition, disagreements, diversity.",
    "Six of Wands": "Victory, success, recognition, self-confidence.",
    "Seven of Wands": "Challenge, perseverance, defense, standing your ground.",
    "Eight of Wands": "Speed, action, movement, swift progress.",
    "Nine of Wands": "Resilience, persistence, boundaries, weariness.",
    "Ten of Wands": "Burden, responsibility, stress, hard work.",
    "King of Wands": "Leadership, vision, charisma, entrepreneurship.",
    "Knight of Wands": "Energy, passion, adventure, impulsiveness.",
    "Page of Wands": "Exploration, enthusiasm, curiosity, potential.",
    "Queen of Wands": "Confidence, courage, determination, independence.",

    # Swords Suit
    "Ace of Swords": "Breakthrough, clarity, sharp mind, new ideas.",
    "Two of Swords": "Indecision, choices, stalemate, difficult decisions.",
    "Three of Swords": "Heartbreak, emotional pain, grief, sorrow.",
    "Four of Swords": "Rest, recovery, contemplation, relaxation.",
    "Five of Swords": "Conflict, tension, loss, betrayal.",
    "Six of Swords": "Transition, moving on, change, leaving behind.",
    "Seven of Swords": "Deception, trickery, strategy, betrayal.",
    "Eight of Swords": "Imprisonment, restriction, self-imposed limitations.",
    "Nine of Swords": "Anxiety, worry, nightmares, fear.",
    "Ten of Swords": "Endings, defeat, backstabbing, betrayal.",
    "King of Swords": "Mental clarity, authority, truth, intellectual power.",
    "Knight of Swords": "Ambition, action, drive, focus.",
    "Page of Swords": "Curiosity, restlessness, mental energy, new ideas.",
    "Queen of Swords": "Perceptiveness, independence, fairness, clear boundaries."
}
